{% set name = "winpty" %}
{% set version = "0.5.4" %}
{% set hash = "4ee8193b19d77ab59097a000a2c52b36e768e92263812e0c0b40306be8927fb4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/rprichard/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ hash }}
  patches:
     - 0001-disable-msys-compiler-check.patch

build:
  number: 4
  skip: True  # [not win]

requirements:
  build:
    - posix
    - m2w64-toolchain

test:
  commands:
    - winpty-agent --version

about:
  home: https://github.com/rprichard/winpty
  license: MIT
  summary: |
    Winpty provides an interface similar to a Unix pty-master for communicating
    with Windows console programs.
  description: |
    Winpty is a Windows software package providing an interface similar to a Unix
    pty-master for communicating with Windows console programs. The package
    consists of a library (libwinpty) and a tool for Cygwin and MSYS for running
    Windows console programs in a Cygwin/MSYS pty.
  doc_url: https://github.com/rprichard/winpty
  dev_url: https://github.com/rprichard/winpty

extra:
  recipe-maintainers:
    - blink1073
    - ccordoba12
    - andfoy
    - jjhelmus
